# Generated by Django 6.0.5 on 2026-06-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('business', 'Business')], max_length=20, null=True),
        ),
    ]
