# Generated by Django 6.0.5 on 2026-06-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='revisions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
