# Generated by Django 6.0.5 on 2026-06-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_rename_offer_offers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferDetail',
            new_name='OfferDetails',
        ),
    ]
