# Generated by Django 6.0.5 on 2026-06-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_rename_offerdetail_offerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
