# Generated by Django 6.0.5 on 2026-06-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0004_offers_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='owner',
            new_name='user',
        ),
    ]
