# Generated by Django 6.0.5 on 2026-06-14 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_rename_owner_offers_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='user',
            new_name='owner',
        ),
    ]
