# Generated by Django 6.0.5 on 2026-06-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_rename_user_offers_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerdetails',
            options={'verbose_name': 'Offer Detail'},
        ),
        migrations.AlterModelOptions(
            name='offers',
            options={'verbose_name': 'Offer'},
        ),
        migrations.AlterField(
            model_name='offerdetails',
            name='offer_type',
            field=models.CharField(choices=[('basic', 'basic'), ('standard', 'standard'), ('premium', 'premium')], max_length=10),
        ),
    ]
