# Generated by Django 6.0.5 on 2026-06-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_reviews_unique_customer_review_per_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review'},
        ),
    ]
