# Generated by Django 6.0.5 on 2026-06-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
